### ISSUE TITLE
Botman incompatible with Symfony cache driver?

### ISSUE THREAD

**Issue by nicodemuz** [mpociot/botman#1411]
- BotMan Version: 2.6.1
- PHP Version: 8.3.11
- Messaging Service(s): Web
- Cache Driver: SymfonyCache

### Description:

I get the following error when trying to use Botman for a Symfony project. It would seem like it's not able to serialize closures?

```
Cannot assign Laravel\\SerializableClosure\\Serializers\\Native to property Symfony\\Component\\HttpFoundation\\Session\\SessionBagProxy::$usageReporter of type ?Closure
```

### Steps To Reproduce:

It happens for the following conversation class:

```php
<?php

declare(strict_types=1);

namespace App\Bot;

use BotMan\BotMan\Messages\Conversations\Conversation;
use BotMan\BotMan\Messages\Incoming\Answer;
use BotMan\BotMan\Messages\Outgoing\Actions\Button;
use BotMan\BotMan\Messages\Outgoing\Question;

class HelpConversation extends Conversation
{
    public function run(): void
    {
        $question = Question::create('Hello, what do you need help with?')
            ->addButtons([
                Button::create('Get support')->value('support')->additionalParameters(['isActionRespondVisible' => true]),
            ]);

        $this->ask($question, function (Answer $answer) {
            // Fails if we try to use "$this" within the function
            $this->say('Got your answer: ' . $answer->getText());
        });
    }
}
```

**Comment by filippotoso** [comment]
How do you instantiate Botman?

**Comment by nicodemuz** [comment]
> How do you instantiate Botman?

```yaml
services:
    botman_filesystem_adapter:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            - 'botman_cache' # name of the cache pool
            - 0 # default lifetime in seconds (0 = no expiration)
            - '%kernel.cache_dir%/botman' # directory where cache files are stored
    BotMan\BotMan\Cache\SymfonyCache:
        arguments:
            - '@botman_filesystem_adapter'
    BotMan\BotMan\BotMan:
        factory: ['App\Factory\BotManFactory', 'create']
        arguments:
            - []
            - '@BotMan\BotMan\Cache\SymfonyCache'
```

```php
<?php

declare(strict_types=1);

namespace App\Factory;

use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory as BaseBotManFactory;
use BotMan\BotMan\Drivers\DriverManager;
use BotMan\BotMan\Interfaces\CacheInterface;
use BotMan\BotMan\Interfaces\StorageInterface;
use BotMan\Drivers\Web\WebDriver;
use Symfony\Component\HttpFoundation\Request;

final class BotManFactory extends BaseBotManFactory
{
    public static function create(
        array $config,
        ?CacheInterface $cache = null,
        ?Request $request = null,
        ?StorageInterface $storageDriver = null
    ): BotMan {
        $botman = parent::create($config, $cache, $request, $storageDriver);

        DriverManager::loadDriver(WebDriver::class);
        $botman->loadDriver(WebDriver::class);

        return $botman;
    }
}
```
